export const cryptocurrencies = {
    "data":{
        "BTC":[
            {
               "id":1, //YUP
               "name":"Bitcoin", //YUP
               "symbol":"BTC", //YUP
               "slug":"bitcoin",
               "logo": "https://s2.coinmarketcap.com/static/img/coins/64x64/1.png",
               "num_market_pairs":9821,
               "date_added":"2013-04-28T00:00:00.000Z",
               "tags":[
                  {
                     "slug":"mineable",
                     "name":"Mineable",
                     "category":"OTHERS"
                  },
                  {
                     "slug":"pow",
                     "name":"PoW",
                     "category":"ALGORITHM"
                  },
                  {
                     "slug":"sha-256",
                     "name":"SHA-256",
                     "category":"ALGORITHM"
                  },
                  {
                     "slug":"store-of-value",
                     "name":"Store Of Value",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"state-channel",
                     "name":"State Channel",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"coinbase-ventures-portfolio",
                     "name":"Coinbase Ventures Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"three-arrows-capital-portfolio",
                     "name":"Three Arrows Capital Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"polychain-capital-portfolio",
                     "name":"Polychain Capital Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"binance-labs-portfolio",
                     "name":"Binance Labs Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"blockchain-capital-portfolio",
                     "name":"Blockchain Capital Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"boostvc-portfolio",
                     "name":"BoostVC Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"cms-holdings-portfolio",
                     "name":"CMS Holdings Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"dcg-portfolio",
                     "name":"DCG Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"dragonfly-capital-portfolio",
                     "name":"DragonFly Capital Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"electric-capital-portfolio",
                     "name":"Electric Capital Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"fabric-ventures-portfolio",
                     "name":"Fabric Ventures Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"framework-ventures-portfolio",
                     "name":"Framework Ventures Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"galaxy-digital-portfolio",
                     "name":"Galaxy Digital Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"huobi-capital-portfolio",
                     "name":"Huobi Capital Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"alameda-research-portfolio",
                     "name":"Alameda Research Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"a16z-portfolio",
                     "name":"a16z Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"1confirmation-portfolio",
                     "name":"1Confirmation Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"winklevoss-capital-portfolio",
                     "name":"Winklevoss Capital Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"usv-portfolio",
                     "name":"USV Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"placeholder-ventures-portfolio",
                     "name":"Placeholder Ventures Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"pantera-capital-portfolio",
                     "name":"Pantera Capital Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"multicoin-capital-portfolio",
                     "name":"Multicoin Capital Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"paradigm-portfolio",
                     "name":"Paradigm Portfolio",
                     "category":"CATEGORY"
                  }
               ],
               "max_supply":21000000,
               "circulating_supply":19199218, //YUP
               "total_supply":19199218,
               "is_active":1,
               "platform":"None",
               "cmc_rank":1, //YUP
               "is_fiat":0,
               "self_reported_circulating_supply":"None",
               "self_reported_market_cap":"None",
               "tvl_ratio":"None",
               "last_updated":"2022-11-05T20:37:00.000Z",
               "quote":{
                  "USD":{
                     "price":21331.980034862474, //YUP
                     "volume_24h":38781282085.64481,
                     "volume_change_24h":-39.25,
                     "percent_change_1h":0.04023341,
                     "percent_change_24h":1.25438275,
                     "percent_change_7d":2.27132922,
                     "percent_change_30d":6.35668827,
                     "percent_change_60d":13.00744708,
                     "percent_change_90d":-8.22854142,
                     "market_cap":409557335060.9722, //YUP
                     "market_cap_dominance":38.6135,
                     "fully_diluted_market_cap":447971580732.11,
                     "tvl":"None",
                     "last_updated":"2022-11-05T20:37:00.000Z"
                  }
               }
            }
         ],
        "ETH":[
            {
               "id":1027,
               "name":"Ethereum",
               "symbol":"ETH",
               "slug":"ethereum",
               "logo": "https://s2.coinmarketcap.com/static/img/coins/64x64/1027.png",
               "num_market_pairs":6171,
               "date_added":"2015-08-07T00:00:00.000Z",
               "tags":[
                  {
                     "slug":"pos",
                     "name":"PoS",
                     "category":"ALGORITHM"
                  },
                  {
                     "slug":"smart-contracts",
                     "name":"Smart Contracts",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"ethereum-ecosystem",
                     "name":"Ethereum Ecosystem",
                     "category":"PLATFORM"
                  },
                  {
                     "slug":"coinbase-ventures-portfolio",
                     "name":"Coinbase Ventures Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"three-arrows-capital-portfolio",
                     "name":"Three Arrows Capital Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"polychain-capital-portfolio",
                     "name":"Polychain Capital Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"binance-labs-portfolio",
                     "name":"Binance Labs Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"blockchain-capital-portfolio",
                     "name":"Blockchain Capital Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"boostvc-portfolio",
                     "name":"BoostVC Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"cms-holdings-portfolio",
                     "name":"CMS Holdings Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"dcg-portfolio",
                     "name":"DCG Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"dragonfly-capital-portfolio",
                     "name":"DragonFly Capital Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"electric-capital-portfolio",
                     "name":"Electric Capital Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"fabric-ventures-portfolio",
                     "name":"Fabric Ventures Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"framework-ventures-portfolio",
                     "name":"Framework Ventures Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"hashkey-capital-portfolio",
                     "name":"Hashkey Capital Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"kenetic-capital-portfolio",
                     "name":"Kenetic Capital Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"huobi-capital-portfolio",
                     "name":"Huobi Capital Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"alameda-research-portfolio",
                     "name":"Alameda Research Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"a16z-portfolio",
                     "name":"a16z Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"1confirmation-portfolio",
                     "name":"1Confirmation Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"winklevoss-capital-portfolio",
                     "name":"Winklevoss Capital Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"usv-portfolio",
                     "name":"USV Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"placeholder-ventures-portfolio",
                     "name":"Placeholder Ventures Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"pantera-capital-portfolio",
                     "name":"Pantera Capital Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"multicoin-capital-portfolio",
                     "name":"Multicoin Capital Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"paradigm-portfolio",
                     "name":"Paradigm Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"injective-ecosystem",
                     "name":"Injective Ecosystem",
                     "category":"PLATFORM"
                  }
               ],
               "max_supply":"None",
               "circulating_supply":122373863.499,
               "total_supply":122373863.499,
               "is_active":1,
               "platform":"None",
               "cmc_rank":2,
               "is_fiat":0,
               "self_reported_circulating_supply":"None",
               "self_reported_market_cap":"None",
               "tvl_ratio":"None",
               "last_updated":"2022-11-05T20:37:00.000Z",
               "quote":{
                  "USD":{
                     "price":1632.0911607828352,
                     "volume_24h":11431083157.872326,
                     "volume_change_24h":-45.1913,
                     "percent_change_1h":0.09338671,
                     "percent_change_24h":-0.60575126,
                     "percent_change_7d":0.23871271,
                     "percent_change_30d":19.9076318,
                     "percent_change_60d":3.9987155,
                     "percent_change_90d":-4.97041986,
                     "market_cap":199725300927.56314,
                     "market_cap_dominance":18.8303,
                     "fully_diluted_market_cap":199725300927.56,
                     "tvl":"None",
                     "last_updated":"2022-11-05T20:37:00.000Z"
                  }
               }
            }
         ],
        "USDT":[
            {
               "id":825,
               "name":"Tether",
               "symbol":"USDT",
               "slug":"tether",
               "logo": "https://s2.coinmarketcap.com/static/img/coins/64x64/825.png",
               "num_market_pairs":41571,
               "date_added":"2015-02-25T00:00:00.000Z",
               "tags":[
                  {
                     "slug":"payments",
                     "name":"Payments",
                     "category":"INDUSTRY"
                  },
                  {
                     "slug":"stablecoin",
                     "name":"Stablecoin",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"asset-backed-stablecoin",
                     "name":"Asset-Backed Stablecoin",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"avalanche-ecosystem",
                     "name":"Avalanche Ecosystem",
                     "category":"PLATFORM"
                  },
                  {
                     "slug":"solana-ecosystem",
                     "name":"Solana Ecosystem",
                     "category":"PLATFORM"
                  },
                  {
                     "slug":"arbitrum-ecosytem",
                     "name":"Arbitrum Ecosystem",
                     "category":"PLATFORM"
                  },
                  {
                     "slug":"moonriver-ecosystem",
                     "name":"Moonriver Ecosystem",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"injective-ecosystem",
                     "name":"Injective Ecosystem",
                     "category":"PLATFORM"
                  },
                  {
                     "slug":"bnb-chain",
                     "name":"BNB Chain",
                     "category":"PLATFORM"
                  },
                  {
                     "slug":"usd-stablecoin",
                     "name":"USD Stablecoin",
                     "category":"CATEGORY"
                  }
               ],
               "max_supply":"None",
               "circulating_supply":69360692563.60567,
               "total_supply":72141766321.66891,
               "platform":{
                  "id":1027,
                  "name":"Ethereum",
                  "symbol":"ETH",
                  "slug":"ethereum",
                  "token_address":"0xdac17f958d2ee523a2206206994597c13d831ec7"
               },
               "is_active":1,
               "cmc_rank":3,
               "is_fiat":0,
               "self_reported_circulating_supply":"None",
               "self_reported_market_cap":"None",
               "tvl_ratio":"None",
               "last_updated":"2022-11-05T20:37:00.000Z",
               "quote":{
                  "USD":{
                     "price":1.0000965440639487,
                     "volume_24h":58502754258.03732,
                     "volume_change_24h":-33.4285,
                     "percent_change_1h":-0.00174034,
                     "percent_change_24h":0.00060678,
                     "percent_change_7d":-0.02019026,
                     "percent_change_30d":-0.00856829,
                     "percent_change_60d":0.00446459,
                     "percent_change_90d":-0.00435472,
                     "market_cap":69367388926.74405,
                     "market_cap_dominance":6.54,
                     "fully_diluted_market_cap":72148731180.97,
                     "tvl":"None",
                     "last_updated":"2022-11-05T20:37:00.000Z"
                  }
               }
            }
         ],
        "BNB":[
            {
               "id":1839,
               "name":"BNB",
               "symbol":"BNB",
               "slug":"bnb",
               "logo": "https://s2.coinmarketcap.com/static/img/coins/64x64/1839.png",
               "num_market_pairs":1134,
               "date_added":"2017-07-25T00:00:00.000Z",
               "tags":[
                  {
                     "slug":"marketplace",
                     "name":"Marketplace",
                     "category":"INDUSTRY"
                  },
                  {
                     "slug":"centralized-exchange",
                     "name":"Centralized Exchange",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"payments",
                     "name":"Payments",
                     "category":"INDUSTRY"
                  },
                  {
                     "slug":"smart-contracts",
                     "name":"Smart Contracts",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"alameda-research-portfolio",
                     "name":"Alameda Research Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"multicoin-capital-portfolio",
                     "name":"Multicoin Capital Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"moonriver-ecosystem",
                     "name":"Moonriver Ecosystem",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"bnb-chain",
                     "name":"BNB Chain",
                     "category":"PLATFORM"
                  }
               ],
               "max_supply":200000000,
               "circulating_supply":159976851.2297294,
               "total_supply":159979963.59042934,
               "is_active":1,
               "platform":"None",
               "cmc_rank":4,
               "is_fiat":0,
               "self_reported_circulating_supply":"None",
               "self_reported_market_cap":"None",
               "tvl_ratio":"None",
               "last_updated":"2022-11-05T20:37:00.000Z",
               "quote":{
                  "USD":{
                     "price":349.8411624137202,
                     "volume_24h":1225173596.2183318,
                     "volume_change_24h":-39.1339,
                     "percent_change_1h":0.1614515,
                     "percent_change_24h":-0.90333869,
                     "percent_change_7d":15.18320757,
                     "percent_change_30d":21.04237011,
                     "percent_change_60d":32.25566608,
                     "percent_change_90d":7.98702664,
                     "market_cap":55966487593.49532,
                     "market_cap_dominance":5.2766,
                     "fully_diluted_market_cap":69968232482.74,
                     "tvl":"None",
                     "last_updated":"2022-11-05T20:37:00.000Z"
                  }
               }
            }
         ],
        "USDC":[
            {
               "id":3408,
               "name":"USD Coin",
               "symbol":"USDC",
               "slug":"usd-coin",
               "logo": "https://s2.coinmarketcap.com/static/img/coins/64x64/3408.png",
               "num_market_pairs":6672,
               "date_added":"2018-10-08T00:00:00.000Z",
               "tags":[
                  {
                     "slug":"medium-of-exchange",
                     "name":"Medium of Exchange",
                     "category":"INDUSTRY"
                  },
                  {
                     "slug":"stablecoin",
                     "name":"Stablecoin",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"asset-backed-stablecoin",
                     "name":"Asset-Backed Stablecoin",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"fantom-ecosystem",
                     "name":"Fantom Ecosystem",
                     "category":"PLATFORM"
                  },
                  {
                     "slug":"arbitrum-ecosytem",
                     "name":"Arbitrum Ecosystem",
                     "category":"PLATFORM"
                  },
                  {
                     "slug":"moonriver-ecosystem",
                     "name":"Moonriver Ecosystem",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"bnb-chain",
                     "name":"BNB Chain",
                     "category":"PLATFORM"
                  },
                  {
                     "slug":"usd-stablecoin",
                     "name":"USD Stablecoin",
                     "category":"CATEGORY"
                  }
               ],
               "max_supply":"None",
               "circulating_supply":42013877662.68438,
               "total_supply":42013877662.68438,
               "platform":{
                  "id":1027,
                  "name":"Ethereum",
                  "symbol":"ETH",
                  "slug":"ethereum",
                  "token_address":"0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"
               },
               "is_active":1,
               "cmc_rank":5,
               "is_fiat":0,
               "self_reported_circulating_supply":"None",
               "self_reported_market_cap":"None",
               "tvl_ratio":"None",
               "last_updated":"2022-11-05T20:37:00.000Z",
               "quote":{
                  "USD":{
                     "price":0.9999933379714019,
                     "volume_24h":2926191687.610131,
                     "volume_change_24h":-29.666,
                     "percent_change_1h":0.00027906,
                     "percent_change_24h":-0.00229996,
                     "percent_change_7d":-0.000572,
                     "percent_change_30d":0.00129839,
                     "percent_change_60d":-0.00161899,
                     "percent_change_90d":-0.0142435,
                     "market_cap":42013597765.02988,
                     "market_cap_dominance":3.961,
                     "fully_diluted_market_cap":42013597765.03,
                     "tvl":"None",
                     "last_updated":"2022-11-05T20:37:00.000Z"
                  }
               }
            }
         ],
        "XRP":[
            {
               "id":52,
               "name":"XRP",
               "symbol":"XRP",
               "slug":"xrp",
               "logo": "https://s2.coinmarketcap.com/static/img/coins/64x64/52.png",
               "num_market_pairs":833,
               "date_added":"2013-08-04T00:00:00.000Z",
               "tags":[
                  {
                     "slug":"medium-of-exchange",
                     "name":"Medium of Exchange",
                     "category":"INDUSTRY"
                  },
                  {
                     "slug":"enterprise-solutions",
                     "name":"Enterprise Solutions",
                     "category":"INDUSTRY"
                  },
                  {
                     "slug":"arrington-xrp-capital-portfolio",
                     "name":"Arrington XRP Capital Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"galaxy-digital-portfolio",
                     "name":"Galaxy Digital Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"a16z-portfolio",
                     "name":"a16z Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"pantera-capital-portfolio",
                     "name":"Pantera Capital Portfolio",
                     "category":"CATEGORY"
                  }
               ],
               "max_supply":100000000000,
               "circulating_supply":50215300844,
               "total_supply":99989233161,
               "is_active":1,
               "platform":"None",
               "cmc_rank":6,
               "is_fiat":0,
               "self_reported_circulating_supply":"None",
               "self_reported_market_cap":"None",
               "tvl_ratio":"None",
               "last_updated":"2022-11-05T20:37:00.000Z",
               "quote":{
                  "USD":{
                     "price":0.5010482602716978,
                     "volume_24h":1297705177.4839323,
                     "volume_change_24h":-51.6044,
                     "percent_change_1h":0.23745165,
                     "percent_change_24h":1.14002096,
                     "percent_change_7d":5.80839027,
                     "percent_change_30d":-0.06437185,
                     "percent_change_60d":55.18381571,
                     "percent_change_90d":33.3030095,
                     "market_cap":25160289126.906116,
                     "market_cap_dominance":2.3721,
                     "fully_diluted_market_cap":50104826027.17,
                     "tvl":"None",
                     "last_updated":"2022-11-05T20:37:00.000Z"
                  }
               }
            }
         ],
        "BUSD":[
            {
               "id":4687,
               "name":"Binance USD",
               "symbol":"BUSD",
               "slug":"binance-usd",
               "logo": "https://s2.coinmarketcap.com/static/img/coins/64x64/4687.png",
               "num_market_pairs":5403,
               "date_added":"2019-09-20T00:00:00.000Z",
               "tags":[
                  {
                     "slug":"stablecoin",
                     "name":"Stablecoin",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"asset-backed-stablecoin",
                     "name":"Asset-Backed Stablecoin",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"binance-chain",
                     "name":"Binance Chain",
                     "category":"PLATFORM"
                  },
                  {
                     "slug":"harmony-ecosystem",
                     "name":"Harmony Ecosystem",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"moonriver-ecosystem",
                     "name":"Moonriver Ecosystem",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"usd-stablecoin",
                     "name":"USD Stablecoin",
                     "category":"CATEGORY"
                  }
               ],
               "max_supply":"None",
               "circulating_supply":22544178441.509254,
               "total_supply":22544178441.509254,
               "platform":{
                  "id":1839,
                  "name":"BNB",
                  "symbol":"BNB",
                  "slug":"bnb",
                  "token_address":"BUSD-BD1"
               },
               "is_active":1,
               "cmc_rank":7,
               "is_fiat":0,
               "self_reported_circulating_supply":"None",
               "self_reported_market_cap":"None",
               "tvl_ratio":"None",
               "last_updated":"2022-11-05T20:37:00.000Z",
               "quote":{
                  "USD":{
                     "price":0.9999950256938842,
                     "volume_24h":7138990054.30494,
                     "volume_change_24h":-29.6357,
                     "percent_change_1h":0.02440069,
                     "percent_change_24h":-0.07616801,
                     "percent_change_7d":-0.02368544,
                     "percent_change_30d":0.00557402,
                     "percent_change_60d":-0.03074923,
                     "percent_change_90d":0.00374736,
                     "market_cap":22544066299.86456,
                     "market_cap_dominance":2.1255,
                     "fully_diluted_market_cap":22544066299.86,
                     "tvl":"None",
                     "last_updated":"2022-11-05T20:37:00.000Z"
                  }
               }
            }
         ],
        "DOGE":[
            {
               "id":74,
               "name":"Dogecoin",
               "symbol":"DOGE",
               "slug":"dogecoin",
               "logo": "https://s2.coinmarketcap.com/static/img/coins/64x64/74.png",
               "num_market_pairs":590,
               "date_added":"2013-12-15T00:00:00.000Z",
               "tags":[
                  {
                     "slug":"mineable",
                     "name":"Mineable",
                     "category":"OTHERS"
                  },
                  {
                     "slug":"pow",
                     "name":"PoW",
                     "category":"ALGORITHM"
                  },
                  {
                     "slug":"scrypt",
                     "name":"Scrypt",
                     "category":"ALGORITHM"
                  },
                  {
                     "slug":"medium-of-exchange",
                     "name":"Medium of Exchange",
                     "category":"INDUSTRY"
                  },
                  {
                     "slug":"memes",
                     "name":"Memes",
                     "category":"INDUSTRY"
                  },
                  {
                     "slug":"payments",
                     "name":"Payments",
                     "category":"INDUSTRY"
                  },
                  {
                     "slug":"doggone-doggerel",
                     "name":"Doggone Doggerel",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"bnb-chain",
                     "name":"BNB Chain",
                     "category":"PLATFORM"
                  }
               ],
               "max_supply":"None",
               "circulating_supply":132670764299.89409,
               "total_supply":132670764299.89409,
               "is_active":1,
               "platform":"None",
               "cmc_rank":8,
               "is_fiat":0,
               "self_reported_circulating_supply":"None",
               "self_reported_market_cap":"None",
               "tvl_ratio":"None",
               "last_updated":"2022-11-05T20:37:00.000Z",
               "quote":{
                  "USD":{
                     "price":0.12724518083110933,
                     "volume_24h":1940352240.8927302,
                     "volume_change_24h":-37.5741,
                     "percent_change_1h":0.08708705,
                     "percent_change_24h":1.60463915,
                     "percent_change_7d":0.13515373,
                     "percent_change_30d":99.22897935,
                     "percent_change_60d":115.42981965,
                     "percent_change_90d":82.6963362,
                     "market_cap":16881715394.341507,
                     "market_cap_dominance":1.5916,
                     "fully_diluted_market_cap":16881715394.34,
                     "tvl":"None",
                     "last_updated":"2022-11-05T20:37:00.000Z"
                  }
               }
            }
         ],
        "ADA":[
            {
                "id":2010,
                "name":"Cardano",
                "symbol":"ADA",
                "slug":"cardano",
                "logo": "https://s2.coinmarketcap.com/static/img/coins/64x64/2010.png",
                "num_market_pairs":585,
                "date_added":"2017-10-01T00:00:00.000Z",
                "tags":[
                    {
                    "slug":"dpos",
                    "name":"DPoS",
                    "category":"ALGORITHM"
                    },
                    {
                    "slug":"pos",
                    "name":"PoS",
                    "category":"ALGORITHM"
                    },
                    {
                    "slug":"platform",
                    "name":"Platform",
                    "category":"CATEGORY"
                    },
                    {
                    "slug":"research",
                    "name":"Research",
                    "category":"INDUSTRY"
                    },
                    {
                    "slug":"smart-contracts",
                    "name":"Smart Contracts",
                    "category":"CATEGORY"
                    },
                    {
                    "slug":"staking",
                    "name":"Staking",
                    "category":"CATEGORY"
                    },
                    {
                    "slug":"cardano-ecosystem",
                    "name":"Cardano Ecosystem",
                    "category":"CATEGORY"
                    },
                    {
                    "slug":"cardano",
                    "name":"Cardano",
                    "category":"PLATFORM"
                    }
                ],
                "max_supply":45000000000,
                "circulating_supply":34340711666.751,
                "total_supply":35101471140.919,
                "is_active":1,
                "platform":"None",
                "cmc_rank":9,
                "is_fiat":0,
                "self_reported_circulating_supply":"None",
                "self_reported_market_cap":"None",
                "tvl_ratio":"None",
                "last_updated":"2022-11-05T20:37:00.000Z",
                "quote":{
                    "USD":{
                    "price":0.42721662322799375,
                    "volume_24h":695203345.3476396,
                    "volume_change_24h":-22.2642,
                    "percent_change_1h":0.22514198,
                    "percent_change_24h":0.78637215,
                    "percent_change_7d":1.86248498,
                    "percent_change_30d":-0.62567687,
                    "percent_change_60d":-8.13172587,
                    "percent_change_90d":-18.68704541,
                    "market_cap":14670922877.515532,
                    "market_cap_dominance":1.3832,
                    "fully_diluted_market_cap":19224748045.26,
                    "tvl":"None",
                    "last_updated":"2022-11-05T20:37:00.000Z"
                    }
                }
            }
        ],
        "SOL":[
            {
               "id":5426,
               "name":"Solana",
               "symbol":"SOL",
               "slug":"solana",
               "logo": "https://s2.coinmarketcap.com/static/img/coins/64x64/5426.png",
               "num_market_pairs":396,
               "date_added":"2020-04-10T00:00:00.000Z",
               "tags":[
                  {
                     "slug":"pos",
                     "name":"PoS",
                     "category":"ALGORITHM"
                  },
                  {
                     "slug":"platform",
                     "name":"Platform",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"solana-ecosystem",
                     "name":"Solana Ecosystem",
                     "category":"PLATFORM"
                  },
                  {
                     "slug":"cms-holdings-portfolio",
                     "name":"CMS Holdings Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"kenetic-capital-portfolio",
                     "name":"Kenetic Capital Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"alameda-research-portfolio",
                     "name":"Alameda Research Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"multicoin-capital-portfolio",
                     "name":"Multicoin Capital Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"okex-blockdream-ventures-portfolio",
                     "name":"OKEx Blockdream Ventures Portfolio",
                     "category":"CATEGORY"
                  }
               ],
               "max_supply":"None",
               "circulating_supply":359223090.5505434,
               "total_supply":511616946.142289,
               "is_active":1,
               "platform":"None",
               "cmc_rank":10,
               "is_fiat":0,
               "self_reported_circulating_supply":"None",
               "self_reported_market_cap":"None",
               "tvl_ratio":"None",
               "last_updated":"2022-11-05T20:37:00.000Z",
               "quote":{
                  "USD":{
                     "price":36.75420735316134,
                     "volume_24h":2361123625.6161375,
                     "volume_change_24h":78.6079,
                     "percent_change_1h":1.19996227,
                     "percent_change_24h":9.82669036,
                     "percent_change_7d":11.30912968,
                     "percent_change_30d":8.90132107,
                     "percent_change_60d":18.360148,
                     "percent_change_90d":-10.14471416,
                     "market_cap":13202959956.138126,
                     "market_cap_dominance":1.2448,
                     "fully_diluted_market_cap":18804075323.9,
                     "tvl":"None",
                     "last_updated":"2022-11-05T20:37:00.000Z"
                  }
               }
            },
            {
               "id":16116,
               "name":"Wrapped Solana",
               "symbol":"SOL",
               "slug":"wrapped-solana",
               "num_market_pairs":109,
               "date_added":"2021-12-16T04:30:23.000Z",
               "tags":[
                  
               ],
               "max_supply":"None",
               "circulating_supply":0,
               "total_supply":0,
               "platform":{
                  "id":5426,
                  "name":"Solana",
                  "symbol":"SOL",
                  "slug":"solana",
                  "token_address":"So11111111111111111111111111111111111111112"
               },
               "is_active":1,
               "cmc_rank":2624,
               "is_fiat":0,
               "self_reported_circulating_supply":"None",
               "self_reported_market_cap":"None",
               "tvl_ratio":"None",
               "last_updated":"2022-11-05T20:37:00.000Z",
               "quote":{
                  "USD":{
                     "price":36.77959253566662,
                     "volume_24h":86814878.97302376,
                     "volume_change_24h":68.7403,
                     "percent_change_1h":1.50433704,
                     "percent_change_24h":10.00273238,
                     "percent_change_7d":11.352349,
                     "percent_change_30d":9.08630797,
                     "percent_change_60d":18.77016405,
                     "percent_change_90d":-9.72758014,
                     "market_cap":0,
                     "market_cap_dominance":0,
                     "fully_diluted_market_cap":0,
                     "tvl":"None",
                     "last_updated":"2022-11-05T20:37:00.000Z"
                  }
               }
            },
            {
               "id":591,
               "name":"Solcoin",
               "symbol":"SOL",
               "slug":"solcoin",
               "num_market_pairs":0,
               "date_added":"2014-09-07T00:00:00.000Z",
               "tags":[
                  {
                     "slug":"mineable",
                     "name":"Mineable",
                     "category":"OTHERS"
                  }
               ],
               "max_supply":"None",
               "circulating_supply":289168250,
               "total_supply":289168250,
               "is_active":0,
               "platform":"None",
               "cmc_rank":"None",
               "is_fiat":0,
               "self_reported_circulating_supply":"None",
               "self_reported_market_cap":"None",
               "tvl_ratio":"None",
               "last_updated":"2015-05-31T16:29:17.000Z",
               "quote":{
                  "USD":{
                     "price":2.32e-06,
                     "volume_24h":0,
                     "volume_change_24h":0,
                     "percent_change_1h":0,
                     "percent_change_24h":0,
                     "percent_change_7d":0,
                     "percent_change_30d":0,
                     "percent_change_60d":0,
                     "percent_change_90d":0,
                     "market_cap":670.8703399999999,
                     "market_cap_dominance":0,
                     "fully_diluted_market_cap":0,
                     "tvl":"None",
                     "last_updated":"2015-05-31T16:29:17.000Z"
                  }
               }
            },
            {
               "id":3333,
               "name":"Sola Token",
               "symbol":"SOL",
               "slug":"sola-token",
               "num_market_pairs":0,
               "date_added":"2018-09-24T00:00:00.000Z",
               "tags":[
                  
               ],
               "max_supply":"None",
               "circulating_supply":28948936.515258,
               "total_supply":127864775,
               "platform":{
                  "id":1027,
                  "name":"Ethereum",
                  "symbol":"ETH",
                  "slug":"ethereum",
                  "token_address":"0x1f54638b7737193ffd86c19ec51907a7c41755d8"
               },
               "is_active":0,
               "cmc_rank":"None",
               "is_fiat":0,
               "self_reported_circulating_supply":"None",
               "self_reported_market_cap":"None",
               "tvl_ratio":"None",
               "last_updated":"2020-07-07T02:17:23.000Z",
               "quote":{
                  "USD":{
                     "price":0.00057061,
                     "volume_24h":0,
                     "volume_change_24h":0,
                     "percent_change_1h":0,
                     "percent_change_24h":0,
                     "percent_change_7d":0,
                     "percent_change_30d":0,
                     "percent_change_60d":0,
                     "percent_change_90d":0,
                     "market_cap":16518.55266497137,
                     "market_cap_dominance":0,
                     "fully_diluted_market_cap":0,
                     "tvl":"None",
                     "last_updated":"2020-07-07T02:17:23.000Z"
                  }
               }
            },
            {
               "id":12003,
               "name":"SOL RUNE - Rune.Game",
               "symbol":"SOL",
               "slug":"sol-rune---rune-game",
               "num_market_pairs":4,
               "date_added":"2021-09-20T21:00:25.000Z",
               "tags":[
                  
               ],
               "max_supply":118852,
               "circulating_supply":0,
               "total_supply":0,
               "platform":{
                  "id":1839,
                  "name":"BNB",
                  "symbol":"BNB",
                  "slug":"bnb",
                  "token_address":"0x4ffd3b8ba90f5430cda7f4cc4c0a80df3cd0e495"
               },
               "is_active":0,
               "cmc_rank":"None",
               "is_fiat":0,
               "self_reported_circulating_supply":"None",
               "self_reported_market_cap":"None",
               "tvl_ratio":"None",
               "last_updated":"2022-10-10T18:25:00.000Z",
               "quote":{
                  "USD":{
                     "price":0.29352748458670946,
                     "volume_24h":0,
                     "volume_change_24h":0,
                     "percent_change_1h":0,
                     "percent_change_24h":0,
                     "percent_change_7d":-0.9199732,
                     "percent_change_30d":-17.24342926,
                     "percent_change_60d":-11.36059494,
                     "percent_change_90d":126.27800523,
                     "market_cap":0,
                     "market_cap_dominance":0,
                     "fully_diluted_market_cap":34886.33,
                     "tvl":"None",
                     "last_updated":"2022-10-10T18:25:00.000Z"
                  }
               }
            }
         ],
        "MATIC":[
            {
               "id":3890,
               "name":"Polygon",
               "symbol":"MATIC",
               "slug":"polygon",
               "logo": "https://s2.coinmarketcap.com/static/img/coins/64x64/3890.png",
               "num_market_pairs":504,
               "date_added":"2019-04-28T00:00:00.000Z",
               "tags":[
                  {
                     "slug":"platform",
                     "name":"Platform",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"enterprise-solutions",
                     "name":"Enterprise Solutions",
                     "category":"INDUSTRY"
                  },
                  {
                     "slug":"scaling",
                     "name":"Scaling",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"state-channel",
                     "name":"State Channel",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"coinbase-ventures-portfolio",
                     "name":"Coinbase Ventures Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"binance-launchpad",
                     "name":"Binance Launchpad",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"binance-labs-portfolio",
                     "name":"Binance Labs Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"polygon-ecosystem",
                     "name":"Polygon Ecosystem",
                     "category":"PLATFORM"
                  },
                  {
                     "slug":"moonriver-ecosystem",
                     "name":"Moonriver Ecosystem",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"injective-ecosystem",
                     "name":"Injective Ecosystem",
                     "category":"PLATFORM"
                  }
               ],
               "max_supply":10000000000,
               "circulating_supply":8734317475.28493,
               "total_supply":10000000000,
               "is_active":1,
               "platform":"None",
               "cmc_rank":11,
               "is_fiat":0,
               "self_reported_circulating_supply":"None",
               "self_reported_market_cap":"None",
               "tvl_ratio":"None",
               "last_updated":"2022-11-05T20:37:00.000Z",
               "quote":{
                  "USD":{
                     "price":1.1935410085985638,
                     "volume_24h":1428598972.2639287,
                     "volume_change_24h":-29.879,
                     "percent_change_1h":-0.00962894,
                     "percent_change_24h":3.21473222,
                     "percent_change_7d":27.41553706,
                     "percent_change_30d":42.15475639,
                     "percent_change_60d":44.56115695,
                     "percent_change_90d":29.62413573,
                     "market_cap":10424766088.871635,
                     "market_cap_dominance":0.9828,
                     "fully_diluted_market_cap":11935410085.99,
                     "tvl":"None",
                     "last_updated":"2022-11-05T20:37:00.000Z"
                  }
               }
            }
         ],
        "DOT":[
            {
               "id":6636,
               "name":"Polkadot",
               "symbol":"DOT",
               "slug":"polkadot-new",
               "logo": "https://s2.coinmarketcap.com/static/img/coins/64x64/6636.png",
               "num_market_pairs":421,
               "date_added":"2020-08-19T00:00:00.000Z",
               "tags":[
                  {
                     "slug":"substrate",
                     "name":"Substrate",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"polkadot",
                     "name":"Polkadot",
                     "category":"PLATFORM"
                  },
                  {
                     "slug":"binance-chain",
                     "name":"Binance Chain",
                     "category":"PLATFORM"
                  },
                  {
                     "slug":"polkadot-ecosystem",
                     "name":"Polkadot Ecosystem",
                     "category":"PLATFORM"
                  },
                  {
                     "slug":"three-arrows-capital-portfolio",
                     "name":"Three Arrows Capital Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"polychain-capital-portfolio",
                     "name":"Polychain Capital Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"arrington-xrp-capital-portfolio",
                     "name":"Arrington XRP Capital Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"blockchain-capital-portfolio",
                     "name":"Blockchain Capital Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"boostvc-portfolio",
                     "name":"BoostVC Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"cms-holdings-portfolio",
                     "name":"CMS Holdings Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"coinfund-portfolio",
                     "name":"Coinfund Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"fabric-ventures-portfolio",
                     "name":"Fabric Ventures Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"fenbushi-capital-portfolio",
                     "name":"Fenbushi Capital Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"hashkey-capital-portfolio",
                     "name":"Hashkey Capital Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"kenetic-capital-portfolio",
                     "name":"Kenetic Capital Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"1confirmation-portfolio",
                     "name":"1Confirmation Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"placeholder-ventures-portfolio",
                     "name":"Placeholder Ventures Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"pantera-capital-portfolio",
                     "name":"Pantera Capital Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"exnetwork-capital-portfolio",
                     "name":"Exnetwork Capital Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"web3",
                     "name":"Web3",
                     "category":"INDUSTRY"
                  },
                  {
                     "slug":"spartan-group",
                     "name":"Spartan Group",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"injective-ecosystem",
                     "name":"Injective Ecosystem",
                     "category":"PLATFORM"
                  },
                  {
                     "slug":"bnb-chain",
                     "name":"BNB Chain",
                     "category":"PLATFORM"
                  }
               ],
               "max_supply":"None",
               "circulating_supply":1133181602.752938,
               "total_supply":1249005273.0781178,
               "is_active":1,
               "platform":"None",
               "cmc_rank":12,
               "is_fiat":0,
               "self_reported_circulating_supply":904869778,
               "self_reported_market_cap":6433327746.807898,
               "tvl_ratio":"None",
               "last_updated":"2022-11-05T20:37:00.000Z",
               "quote":{
                  "USD":{
                     "price":7.109672466934682,
                     "volume_24h":462881855.2298942,
                     "volume_change_24h":-10.7836,
                     "percent_change_1h":0.13210804,
                     "percent_change_24h":1.97171972,
                     "percent_change_7d":6.29160272,
                     "percent_change_30d":11.63462113,
                     "percent_change_60d":3.05945168,
                     "percent_change_90d":-19.33428034,
                     "market_cap":8056550041.1294775,
                     "market_cap_dominance":0.7596,
                     "fully_diluted_market_cap":8880018401.06,
                     "tvl":"None",
                     "last_updated":"2022-11-05T20:37:00.000Z"
                  }
               }
            }
         ],
        "SHIB":[
            {
               "id":5994,
               "name":"Shiba Inu",
               "symbol":"SHIB",
               "slug":"shiba-inu",
               "logo": "https://s2.coinmarketcap.com/static/img/coins/64x64/5994.png",
               "num_market_pairs":433,
               "date_added":"2020-08-01T00:00:00.000Z",
               "tags":[
                  {
                     "slug":"memes",
                     "name":"Memes",
                     "category":"INDUSTRY"
                  },
                  {
                     "slug":"ethereum-ecosystem",
                     "name":"Ethereum Ecosystem",
                     "category":"PLATFORM"
                  },
                  {
                     "slug":"doggone-doggerel",
                     "name":"Doggone Doggerel",
                     "category":"CATEGORY"
                  }
               ],
               "max_supply":"None",
               "circulating_supply":549063278876301.94,
               "total_supply":589735030408322.8,
               "platform":{
                  "id":1027,
                  "name":"Ethereum",
                  "symbol":"ETH",
                  "slug":"ethereum",
                  "token_address":"0x95ad61b0a150d79219dcf64e1e6cc01f0b64c4ce"
               },
               "is_active":1,
               "cmc_rank":13,
               "is_fiat":0,
               "self_reported_circulating_supply":"None",
               "self_reported_market_cap":"None",
               "tvl_ratio":"None",
               "last_updated":"2022-11-05T20:37:00.000Z",
               "quote":{
                  "USD":{
                     "price":1.2597662989883303e-05,
                     "volume_24h":562366690.4940796,
                     "volume_change_24h":-21.4659,
                     "percent_change_1h":0.02095328,
                     "percent_change_24h":0.31279866,
                     "percent_change_7d":-4.39378554,
                     "percent_change_30d":11.79642443,
                     "percent_change_60d":6.07647622,
                     "percent_change_90d":4.14472228,
                     "market_cap":6916914147.403964,
                     "market_cap_dominance":0.6521,
                     "fully_diluted_market_cap":7429283166.41,
                     "tvl":"None",
                     "last_updated":"2022-11-05T20:37:00.000Z"
                  }
               }
            }
         ],
        "DAI":[
            {
               "id":4943,
               "name":"Dai",
               "symbol":"DAI",
               "logo": "https://s2.coinmarketcap.com/static/img/coins/64x64/4943.png",
               "slug":"multi-collateral-dai",
               "num_market_pairs":1458,
               "date_added":"2019-11-22T00:00:00.000Z",
               "tags":[
                  {
                     "slug":"defi",
                     "name":"DeFi",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"stablecoin",
                     "name":"Stablecoin",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"asset-backed-stablecoin",
                     "name":"Asset-Backed Stablecoin",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"ethereum-ecosystem",
                     "name":"Ethereum Ecosystem",
                     "category":"PLATFORM"
                  },
                  {
                     "slug":"avalanche-ecosystem",
                     "name":"Avalanche Ecosystem",
                     "category":"PLATFORM"
                  },
                  {
                     "slug":"polygon-ecosystem",
                     "name":"Polygon Ecosystem",
                     "category":"PLATFORM"
                  },
                  {
                     "slug":"fantom-ecosystem",
                     "name":"Fantom Ecosystem",
                     "category":"PLATFORM"
                  },
                  {
                     "slug":"arbitrum-ecosytem",
                     "name":"Arbitrum Ecosystem",
                     "category":"PLATFORM"
                  },
                  {
                     "slug":"harmony-ecosystem",
                     "name":"Harmony Ecosystem",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"moonriver-ecosystem",
                     "name":"Moonriver Ecosystem",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"bnb-chain",
                     "name":"BNB Chain",
                     "category":"PLATFORM"
                  },
                  {
                     "slug":"usd-stablecoin",
                     "name":"USD Stablecoin",
                     "category":"CATEGORY"
                  }
               ],
               "max_supply":"None",
               "circulating_supply":6170092219.066344,
               "total_supply":6170092219.066344,
               "platform":{
                  "id":1027,
                  "name":"Ethereum",
                  "symbol":"ETH",
                  "slug":"ethereum",
                  "token_address":"0x6b175474e89094c44da98b954eedeac495271d0f"
               },
               "is_active":1,
               "cmc_rank":14,
               "is_fiat":0,
               "self_reported_circulating_supply":"None",
               "self_reported_market_cap":"None",
               "tvl_ratio":"None",
               "last_updated":"2022-11-05T20:37:00.000Z",
               "quote":{
                  "USD":{
                     "price":1.000029391290761,
                     "volume_24h":250006507.59791496,
                     "volume_change_24h":-21.7164,
                     "percent_change_1h":0.06246341,
                     "percent_change_24h":0.00360202,
                     "percent_change_7d":0.00393263,
                     "percent_change_30d":0.01663528,
                     "percent_change_60d":0.14427857,
                     "percent_change_90d":0.00728482,
                     "market_cap":6170273566.040777,
                     "market_cap_dominance":0.5817,
                     "fully_diluted_market_cap":6170273566.04,
                     "tvl":"None",
                     "last_updated":"2022-11-05T20:37:00.000Z"
                  }
               }
            }
         ],
        "AVAX":[
            {
               "id":5805,
               "name":"Avalanche",
               "symbol":"AVAX",
               "slug":"avalanche",
               "logo": "https://s2.coinmarketcap.com/static/img/coins/64x64/5805.png",
               "num_market_pairs":337,
               "date_added":"2020-07-13T00:00:00.000Z",
               "tags":[
                  {
                     "slug":"defi",
                     "name":"DeFi",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"smart-contracts",
                     "name":"Smart Contracts",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"three-arrows-capital-portfolio",
                     "name":"Three Arrows Capital Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"polychain-capital-portfolio",
                     "name":"Polychain Capital Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"avalanche-ecosystem",
                     "name":"Avalanche Ecosystem",
                     "category":"PLATFORM"
                  },
                  {
                     "slug":"cms-holdings-portfolio",
                     "name":"CMS Holdings Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"dragonfly-capital-portfolio",
                     "name":"DragonFly Capital Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"moonriver-ecosystem",
                     "name":"Moonriver Ecosystem",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"injective-ecosystem",
                     "name":"Injective Ecosystem",
                     "category":"PLATFORM"
                  }
               ],
               "max_supply":720000000,
               "circulating_supply":299129903.776873,
               "total_supply":404229626.49901325,
               "is_active":1,
               "platform":"None",
               "cmc_rank":15,
               "is_fiat":0,
               "self_reported_circulating_supply":"None",
               "self_reported_market_cap":"None",
               "tvl_ratio":"None",
               "last_updated":"2022-11-05T20:37:00.000Z",
               "quote":{
                  "USD":{
                     "price":19.832824721251583,
                     "volume_24h":373695563.0570408,
                     "volume_change_24h":1.5608,
                     "percent_change_1h":0.49448238,
                     "percent_change_24h":2.9090603,
                     "percent_change_7d":7.47662813,
                     "percent_change_30d":15.67273686,
                     "percent_change_60d":7.71162943,
                     "percent_change_90d":-29.02935056,
                     "market_cap":5932590950.491574,
                     "market_cap_dominance":0.5593,
                     "fully_diluted_market_cap":14279633799.3,
                     "tvl":"None",
                     "last_updated":"2022-11-05T20:37:00.000Z"
                  }
               }
            }
         ],
        "TRX":[
            {
               "id":1958,
               "name":"TRON",
               "symbol":"TRX",
               "slug":"tron",
               "logo": "https://s2.coinmarketcap.com/static/img/coins/64x64/1958.png",
               "num_market_pairs":701,
               "date_added":"2017-09-13T00:00:00.000Z",
               "tags":[
                  {
                     "slug":"media",
                     "name":"Media",
                     "category":"INDUSTRY"
                  },
                  {
                     "slug":"payments",
                     "name":"Payments",
                     "category":"INDUSTRY"
                  },
                  {
                     "slug":"tron-ecosystem",
                     "name":"TRON Ecosystem",
                     "category":"PLATFORM"
                  }
               ],
               "max_supply":"None",
               "circulating_supply":92238874435.40076,
               "total_supply":92238874138.8812,
               "is_active":1,
               "platform":"None",
               "cmc_rank":16,
               "is_fiat":0,
               "self_reported_circulating_supply":71659659264,
               "self_reported_market_cap":4582125118.110826,
               "tvl_ratio":"None",
               "last_updated":"2022-11-05T20:37:00.000Z",
               "quote":{
                  "USD":{
                     "price":0.06394288174368656,
                     "volume_24h":365958559.2393638,
                     "volume_change_24h":3.2401,
                     "percent_change_1h":0.01370886,
                     "percent_change_24h":0.90583591,
                     "percent_change_7d":-0.23724824,
                     "percent_change_30d":2.16404437,
                     "percent_change_60d":5.16144086,
                     "percent_change_90d":-8.76535346,
                     "market_cap":5898019440.193584,
                     "market_cap_dominance":0.5561,
                     "fully_diluted_market_cap":5898019421.23,
                     "tvl":"None",
                     "last_updated":"2022-11-05T20:37:00.000Z"
                  }
               }
            }
         ],
        "UNI":[
            {
               "id":7083,
               "name":"Uniswap",
               "symbol":"UNI",
               "slug":"uniswap",
               "logo": "https://s2.coinmarketcap.com/static/img/coins/64x64/7083.png",
               "num_market_pairs":510,
               "date_added":"2020-09-17T00:00:00.000Z",
               "tags":[
                  {
                     "slug":"decentralized-exchange",
                     "name":"Decentralized Exchange",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"defi",
                     "name":"DeFi",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"dao",
                     "name":"DAO",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"yield-farming",
                     "name":"Yield Farming",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"amm",
                     "name":"AMM",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"coinbase-ventures-portfolio",
                     "name":"Coinbase Ventures Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"three-arrows-capital-portfolio",
                     "name":"Three Arrows Capital Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"governance",
                     "name":"Governance",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"blockchain-capital-portfolio",
                     "name":"Blockchain Capital Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"defiance-capital-portfolio",
                     "name":"DeFiance Capital Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"alameda-research-portfolio",
                     "name":"Alameda Research Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"a16z-portfolio",
                     "name":"a16z Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"pantera-capital-portfolio",
                     "name":"Pantera Capital Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"parafi-capital",
                     "name":"ParaFi Capital",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"paradigm-portfolio",
                     "name":"Paradigm Portfolio",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"arbitrum-ecosytem",
                     "name":"Arbitrum Ecosystem",
                     "category":"PLATFORM"
                  },
                  {
                     "slug":"injective-ecosystem",
                     "name":"Injective Ecosystem",
                     "category":"PLATFORM"
                  }
               ],
               "max_supply":1000000000,
               "circulating_supply":762209326.5354977,
               "total_supply":1000000000,
               "platform":{
                  "id":1027,
                  "name":"Ethereum",
                  "symbol":"ETH",
                  "slug":"ethereum",
                  "token_address":"0x1f9840a85d5af5bf1d1762f925bdaddc4201f984"
               },
               "is_active":1,
               "cmc_rank":17,
               "is_fiat":0,
               "self_reported_circulating_supply":"None",
               "self_reported_market_cap":"None",
               "tvl_ratio":1.33564742,
               "last_updated":"2022-11-05T20:37:00.000Z",
               "quote":{
                  "USD":{
                     "price":7.660865900317361,
                     "volume_24h":194938265.4163516,
                     "volume_change_24h":-34.5092,
                     "percent_change_1h":0.44543543,
                     "percent_change_24h":1.74206223,
                     "percent_change_7d":8.45191656,
                     "percent_change_30d":10.55792406,
                     "percent_change_60d":30.48269185,
                     "percent_change_90d":-14.38860515,
                     "market_cap":5839183438.559655,
                     "market_cap_dominance":0.5505,
                     "fully_diluted_market_cap":7660865900.32,
                     "tvl":4371800034.65109,
                     "last_updated":"2022-11-05T20:37:00.000Z"
                  }
               }
            },
            {
               "id":4307,
               "name":"UNICORN Token",
               "symbol":"UNI",
               "slug":"unicorn-token",
               "num_market_pairs":2,
               "date_added":"2019-08-29T00:00:00.000Z",
               "tags":[
                  
               ],
               "max_supply":"None",
               "circulating_supply":106912508.514,
               "total_supply":9800000000,
               "platform":{
                  "id":1027,
                  "name":"Ethereum",
                  "symbol":"ETH",
                  "slug":"ethereum",
                  "token_address":"0x2730d6fdc86c95a74253beffaa8306b40fedecbb"
               },
               "is_active":1,
               "cmc_rank":2126,
               "is_fiat":0,
               "self_reported_circulating_supply":"None",
               "self_reported_market_cap":"None",
               "tvl_ratio":"None",
               "last_updated":"2022-11-05T20:37:00.000Z",
               "quote":{
                  "USD":{
                     "price":0.0010223141435820736,
                     "volume_24h":367180.38544165,
                     "volume_change_24h":-2.2543,
                     "percent_change_1h":0.02353914,
                     "percent_change_24h":1.26389783,
                     "percent_change_7d":-2.10882118,
                     "percent_change_30d":2448.519793,
                     "percent_change_60d":983.15413098,
                     "percent_change_90d":999.51420277,
                     "market_cap":109298.16957970106,
                     "market_cap_dominance":0,
                     "fully_diluted_market_cap":10018678.61,
                     "tvl":"None",
                     "last_updated":"2022-11-05T20:37:00.000Z"
                  }
               }
            },
            {
               "id":126,
               "name":"UniteCoin",
               "symbol":"UNI",
               "slug":"unitecoin",
               "num_market_pairs":"None",
               "date_added":"2014-04-16T00:00:00.000Z",
               "tags":[
                  {
                     "slug":"mineable",
                     "name":"Mineable",
                     "category":"OTHERS"
                  }
               ],
               "max_supply":"None",
               "circulating_supply":"None",
               "total_supply":"None",
               "is_active":0,
               "platform":"None",
               "cmc_rank":"None",
               "is_fiat":0,
               "self_reported_circulating_supply":"None",
               "self_reported_market_cap":"None",
               "tvl_ratio":"None",
               "last_updated":"2022-11-05T20:39:11.892Z",
               "quote":{
                  "USD":{
                     "price":0,
                     "volume_24h":"None",
                     "volume_change_24h":"None",
                     "percent_change_1h":"None",
                     "percent_change_24h":"None",
                     "percent_change_7d":"None",
                     "percent_change_30d":"None",
                     "percent_change_60d":"None",
                     "percent_change_90d":"None",
                     "market_cap":"None",
                     "market_cap_dominance":"None",
                     "fully_diluted_market_cap":"None",
                     "tvl":"None",
                     "last_updated":"2022-11-05T20:39:11.892Z"
                  }
               }
            },
            {
               "id":1605,
               "name":"Universe",
               "symbol":"UNI",
               "slug":"universe",
               "num_market_pairs":1,
               "date_added":"2017-04-01T00:00:00.000Z",
               "tags":[
                  {
                     "slug":"pos",
                     "name":"PoS",
                     "category":"ALGORITHM"
                  },
                  {
                     "slug":"scrypt",
                     "name":"Scrypt",
                     "category":"ALGORITHM"
                  },
                  {
                     "slug":"bnb-chain",
                     "name":"BNB Chain",
                     "category":"PLATFORM"
                  }
               ],
               "max_supply":"None",
               "circulating_supply":88029748.67654727,
               "total_supply":99229748.67654727,
               "is_active":0,
               "platform":"None",
               "cmc_rank":"None",
               "is_fiat":0,
               "self_reported_circulating_supply":"None",
               "self_reported_market_cap":"None",
               "tvl_ratio":"None",
               "last_updated":"2021-06-26T13:22:07.000Z",
               "quote":{
                  "USD":{
                     "price":0.0015826462413,
                     "volume_24h":0,
                     "volume_change_24h":0,
                     "percent_change_1h":0.14304654,
                     "percent_change_24h":-3.88402227,
                     "percent_change_7d":-11.63882351,
                     "percent_change_30d":-33.9052986,
                     "percent_change_60d":98.65006423,
                     "percent_change_90d":80.07836656,
                     "market_cap":139319.95086552118,
                     "market_cap_dominance":0,
                     "fully_diluted_market_cap":157045.59,
                     "tvl":"None",
                     "last_updated":"2021-06-26T13:22:07.000Z"
                  }
               }
            },
            {
               "id":4113,
               "name":"UNI COIN",
               "symbol":"UNI",
               "slug":"uni-coin",
               "num_market_pairs":1,
               "date_added":"2019-07-17T00:00:00.000Z",
               "tags":[
                  {
                     "slug":"medium-of-exchange",
                     "name":"Medium of Exchange",
                     "category":"INDUSTRY"
                  }
               ],
               "max_supply":"None",
               "circulating_supply":0,
               "total_supply":0,
               "platform":{
                  "id":1027,
                  "name":"Ethereum",
                  "symbol":"ETH",
                  "slug":"ethereum",
                  "token_address":"0xe6877ea9c28fbdec631ffbc087956d0023a76bf2"
               },
               "is_active":0,
               "cmc_rank":"None",
               "is_fiat":0,
               "self_reported_circulating_supply":"None",
               "self_reported_market_cap":"None",
               "tvl_ratio":"None",
               "last_updated":"2021-01-13T05:15:03.000Z",
               "quote":{
                  "USD":{
                     "price":0.49802814018735,
                     "volume_24h":0,
                     "volume_change_24h":0,
                     "percent_change_1h":0.05524619,
                     "percent_change_24h":-0.04133914,
                     "percent_change_7d":-0.13658557,
                     "percent_change_30d":-0.02732742,
                     "percent_change_60d":0,
                     "percent_change_90d":0,
                     "market_cap":0,
                     "market_cap_dominance":0,
                     "fully_diluted_market_cap":0,
                     "tvl":"None",
                     "last_updated":"2021-01-13T05:15:03.000Z"
                  }
               }
            }
         ],
        "WBTC":[
            {
               "id":3717,
               "name":"Wrapped Bitcoin",
               "symbol":"WBTC",
               "slug":"wrapped-bitcoin",
               "logo": "https://s2.coinmarketcap.com/static/img/coins/64x64/3717.png",
               "num_market_pairs":641,
               "date_added":"2019-01-30T00:00:00.000Z",
               "tags":[
                  {
                     "slug":"medium-of-exchange",
                     "name":"Medium of Exchange",
                     "category":"INDUSTRY"
                  },
                  {
                     "slug":"defi",
                     "name":"DeFi",
                     "category":"CATEGORY"
                  },
                  {
                     "slug":"wrapped-tokens",
                     "name":"Wrapped Tokens",
                     "category":"PLATFORM"
                  },
                  {
                     "slug":"fantom-ecosystem",
                     "name":"Fantom Ecosystem",
                     "category":"PLATFORM"
                  },
                  {
                     "slug":"arbitrum-ecosytem",
                     "name":"Arbitrum Ecosystem",
                     "category":"PLATFORM"
                  },
                  {
                     "slug":"moonriver-ecosystem",
                     "name":"Moonriver Ecosystem",
                     "category":"CATEGORY"
                  }
               ],
               "max_supply":"None",
               "circulating_supply":245479.74136945,
               "total_supply":245479.74136945,
               "platform":{
                  "id":1027,
                  "name":"Ethereum",
                  "symbol":"ETH",
                  "slug":"ethereum",
                  "token_address":"0x2260fac5e5542a773aa44fbcfedf7c193bc2c599"
               },
               "is_active":1,
               "cmc_rank":18,
               "is_fiat":0,
               "self_reported_circulating_supply":"None",
               "self_reported_market_cap":"None",
               "tvl_ratio":"None",
               "last_updated":"2022-11-05T20:37:00.000Z",
               "quote":{
                  "USD":{
                     "price":21331.432897798128,
                     "volume_24h":64385988.98946634,
                     "volume_change_24h":-55.8097,
                     "percent_change_1h":0.13311588,
                     "percent_change_24h":1.32845207,
                     "percent_change_7d":2.23357276,
                     "percent_change_30d":6.38915095,
                     "percent_change_60d":12.98391224,
                     "percent_change_90d":-8.18577825,
                     "market_cap":5236434630.791262,
                     "market_cap_dominance":0.4937,
                     "fully_diluted_market_cap":5236434630.79,
                     "tvl":"None",
                     "last_updated":"2022-11-05T20:37:00.000Z"
                  }
               }
            },
            {
               "id":4666,
               "name":"WorldBTC",
               "symbol":"WBTC",
               "slug":"worldbtc",
               "num_market_pairs":"None",
               "date_added":"2019-09-17T00:00:00.000Z",
               "tags":[
                  
               ],
               "max_supply":"None",
               "circulating_supply":"None",
               "total_supply":"None",
               "is_active":0,
               "platform":"None",
               "cmc_rank":"None",
               "is_fiat":0,
               "self_reported_circulating_supply":"None",
               "self_reported_market_cap":"None",
               "tvl_ratio":"None",
               "last_updated":"2022-11-05T20:39:11.898Z",
               "quote":{
                  "USD":{
                     "price":0,
                     "volume_24h":"None",
                     "volume_change_24h":"None",
                     "percent_change_1h":"None",
                     "percent_change_24h":"None",
                     "percent_change_7d":"None",
                     "percent_change_30d":"None",
                     "percent_change_60d":"None",
                     "percent_change_90d":"None",
                     "market_cap":"None",
                     "market_cap_dominance":"None",
                     "fully_diluted_market_cap":"None",
                     "tvl":"None",
                     "last_updated":"2022-11-05T20:39:11.898Z"
                  }
               }
            }
         ],
        "LTC":[
            {
               "id":2,
               "name":"Litecoin",
               "symbol":"LTC",
               "slug":"litecoin",
               "logo": "https://s2.coinmarketcap.com/static/img/coins/64x64/2.png",
               "num_market_pairs":839,
               "date_added":"2013-04-28T00:00:00.000Z",
               "tags":[
                  {
                     "slug":"mineable",
                     "name":"Mineable",
                     "category":"OTHERS"
                  },
                  {
                     "slug":"pow",
                     "name":"PoW",
                     "category":"ALGORITHM"
                  },
                  {
                     "slug":"scrypt",
                     "name":"Scrypt",
                     "category":"ALGORITHM"
                  },
                  {
                     "slug":"medium-of-exchange",
                     "name":"Medium of Exchange",
                     "category":"INDUSTRY"
                  }
               ],
               "max_supply":84000000,
               "circulating_supply":71546406.22976825,
               "total_supply":84000000,
               "is_active":1,
               "platform":"None",
               "cmc_rank":19,
               "is_fiat":0,
               "self_reported_circulating_supply":"None",
               "self_reported_market_cap":"None",
               "tvl_ratio":"None",
               "last_updated":"2022-11-05T20:37:00.000Z",
               "quote":{
                  "USD":{
                     "price":70.49275263403801,
                     "volume_24h":1589485735.785729,
                     "volume_change_24h":-21.7871,
                     "percent_change_1h":1.14799427,
                     "percent_change_24h":2.97223466,
                     "percent_change_7d":24.2455544,
                     "percent_change_30d":31.07137919,
                     "percent_change_60d":28.14933267,
                     "percent_change_90d":14.03589833,
                     "market_cap":5043503116.209449,
                     "market_cap_dominance":0.4755,
                     "fully_diluted_market_cap":5921391221.26,
                     "tvl":"None",
                     "last_updated":"2022-11-05T20:37:00.000Z"
                  }
               }
            }
         ],
        "ATOM":[
            {
                "id":3794,
                "name":"Cosmos",
                "symbol":"ATOM",
                "slug":"cosmos",
                "logo": "https://s2.coinmarketcap.com/static/img/coins/64x64/3794.png",
                "num_market_pairs":356,
                "date_added":"2019-03-14T00:00:00.000Z",
                "tags":[
                    {
                    "slug":"platform",
                    "name":"Platform",
                    "category":"CATEGORY"
                    },
                    {
                    "slug":"cosmos-ecosystem",
                    "name":"Cosmos Ecosystem",
                    "category":"INDUSTRY"
                    },
                    {
                    "slug":"content-creation",
                    "name":"Content Creation",
                    "category":"INDUSTRY"
                    },
                    {
                    "slug":"interoperability",
                    "name":"Interoperability",
                    "category":"CATEGORY"
                    },
                    {
                    "slug":"polychain-capital-portfolio",
                    "name":"Polychain Capital Portfolio",
                    "category":"CATEGORY"
                    },
                    {
                    "slug":"dragonfly-capital-portfolio",
                    "name":"DragonFly Capital Portfolio",
                    "category":"CATEGORY"
                    },
                    {
                    "slug":"hashkey-capital-portfolio",
                    "name":"Hashkey Capital Portfolio",
                    "category":"CATEGORY"
                    },
                    {
                    "slug":"1confirmation-portfolio",
                    "name":"1Confirmation Portfolio",
                    "category":"CATEGORY"
                    },
                    {
                    "slug":"paradigm-portfolio",
                    "name":"Paradigm Portfolio",
                    "category":"CATEGORY"
                    },
                    {
                    "slug":"exnetwork-capital-portfolio",
                    "name":"Exnetwork Capital Portfolio",
                    "category":"CATEGORY"
                    },
                    {
                    "slug":"injective-ecosystem",
                    "name":"Injective Ecosystem",
                    "category":"PLATFORM"
                    }
                ],
                "max_supply":"None",
                "circulating_supply":286370297,
                "total_supply":0,
                "is_active":1,
                "platform":"None",
                "cmc_rank":20,
                "is_fiat":0,
                "self_reported_circulating_supply":"None",
                "self_reported_market_cap":"None",
                "tvl_ratio":"None",
                "last_updated":"2022-11-05T20:37:00.000Z",
                "quote":{
                    "USD":{
                    "price":15.554572450312174,
                    "volume_24h":348866747.8468368,
                    "volume_change_24h":-25.3664,
                    "percent_change_1h":-0.5195616,
                    "percent_change_24h":4.27992243,
                    "percent_change_7d":14.0163085,
                    "percent_change_30d":18.45559513,
                    "percent_change_60d":29.34591135,
                    "percent_change_90d":36.36656095,
                    "market_cap":4454367532.303915,
                    "market_cap_dominance":0.4199,
                    "fully_diluted_market_cap":0,
                    "tvl":"None",
                    "last_updated":"2022-11-05T20:37:00.000Z"
                    }
                }
            },
            {
                "id":1420,
                "name":"Atomic Coin",
                "symbol":"ATOM",
                "slug":"atomic-coin",
                "num_market_pairs":0,
                "date_added":"2016-10-09T00:00:00.000Z",
                "tags":[
                    {
                    "slug":"mineable",
                    "name":"Mineable",
                    "category":"OTHERS"
                    },
                    {
                    "slug":"hybrid-pow-pos",
                    "name":"Hybrid - PoW & PoS",
                    "category":"ALGORITHM"
                    },
                    {
                    "slug":"scrypt",
                    "name":"Scrypt",
                    "category":"ALGORITHM"
                    }
                ],
                "max_supply":252000000,
                "circulating_supply":18554847.3005747,
                "total_supply":18554847.3005747,
                "is_active":0,
                "platform":"None",
                "cmc_rank":"None",
                "is_fiat":0,
                "self_reported_circulating_supply":"None",
                "self_reported_market_cap":"None",
                "tvl_ratio":"None",
                "last_updated":"2019-10-23T03:34:01.000Z",
                "quote":{
                    "USD":{
                    "price":0.00014288,
                    "volume_24h":0,
                    "volume_change_24h":0,
                    "percent_change_1h":0,
                    "percent_change_24h":0,
                    "percent_change_7d":0,
                    "percent_change_30d":0,
                    "percent_change_60d":0,
                    "percent_change_90d":0,
                    "market_cap":2651.1165823061133,
                    "market_cap_dominance":0,
                    "fully_diluted_market_cap":0,
                    "tvl":"None",
                    "last_updated":"2019-10-23T03:34:01.000Z"
                    }
                }
            }
         ],
    }
 }